version: '3.8'


services:
 # DATABASE
 postgres:
    image: postgres:16-alpine
    container_name: insight-postgres
    environment:
      - POSTGRES_USER: insight
      - POSTGRES_PASSWORD: insight123
      - POSTGRES_DB: insight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insight"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CACHE
    redis:
      image: redis:7-alpine
      container_name: insight-redis
      ports:
        - "6379:6379"
      command: redis-server --appendoly yes
      volumes:
       - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  # MESSEAGE QUEUE
    kafka:
      image: bitami/kafka:3.6
      container_name: insight-kafka
      environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      ports: 
       - "9092:9092"
      volumes:
        - kafka_data:/bitami/kafka
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "kafka-topics.sh --bootstrap-server localhost:9092 --list",
          ]
        interval: 30s
        timeout: 10s
        retries: 5